# Generated by Django 3.1 on 2020-09-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='index_number',
            field=models.IntegerField(unique=True, verbose_name='index number'),
        ),
    ]
