# Generated by Django 3.1 on 2020-09-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200904_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='index_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='index number'),
        ),
    ]
