# Generated by Django 3.1 on 2020-09-04 19:43

import assignment.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='activity/')),
                ('index', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('q_number', models.IntegerField()),
                ('date_submitted', models.DateField(default=assignment.utils.Utils.get_date)),
                ('date_created', models.DateTimeField(default=assignment.utils.Utils.get_date_time)),
                ('course', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SelectCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(choices=[('', 'select semester'), ('semester one', 'SEMESTER ONE'), ('semester two', 'SEMESTER TWO')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentOtherCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_course', models.CharField(max_length=200)),
                ('selectcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.selectcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='activity/')),
                ('date_created', models.DateField(default=assignment.utils.Utils.get_date_time)),
                ('course', models.CharField(max_length=200)),
                ('date_to_be_subm', models.DateField(default=assignment.utils.Utils.get_date_time)),
                ('selectcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.selectcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_number', models.IntegerField()),
                ('title', models.CharField(choices=[('', 'select title'), ('assignment', 'Assignment'), ('exercise', 'Exercise'), ('quiz', 'Quiz')], max_length=50)),
                ('status', models.CharField(choices=[('', 'select status'), ('graded', 'graded'), ('not graded', 'not graded')], max_length=50)),
                ('scored', models.FloatField()),
                ('total', models.FloatField()),
                ('course', models.CharField(max_length=200)),
                ('marker', models.CharField(max_length=200)),
                ('date_graded', models.DateField(default=assignment.utils.Utils.get_date)),
                ('date_graded1', models.DateTimeField(default=assignment.utils.Utils.get_date_time)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment')),
                ('studentothercourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.studentothercourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('', 'Select a course'), ('Integral Equations', 'Integral Equations'), ('Real Functions', 'Real Functions')], max_length=100)),
                ('class_or_level', models.CharField(choices=[('', 'Select class'), ('Math1', 'Math 1'), ('Math2', 'Math 2'), ('Math3', 'Math 3'), ('Math4', 'Math 4')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/')),
                ('attachment', models.FileField(upload_to='attachments/')),
                ('phone', models.CharField(max_length=10)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='studentothercourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.studentothercourse'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
